import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: "Netflix 1 écran 4K",
        price: 2500,
        originalPrice: 3000,
        category: "streaming",
        description: "Abonnement Netflix 1 écran 4K - 1 mois",
        icon: "Play",
        color: "from-red-500 to-red-600",
        rating: 4.8,
        reviews: 1200,
        features: JSON.stringify(["1 écran", "Qualité 4K", "Sans publicité"]),
        stock: 100,
        popular: true,
        duration: "1 mois",
      },
      {
        name: "Netflix 2 écrans 4K",
        price: 4000,
        originalPrice: 5000,
        category: "streaming",
        description: "Abonnement Netflix 2 écrans 4K - 1 mois",
        icon: "Play",
        color: "from-red-500 to-red-600",
        rating: 4.8,
        reviews: 900,
        features: JSON.stringify(["2 écrans", "Qualité 4K", "Sans publicité"]),
        stock: 80,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Netflix Personnel",
        price: 6500,
        originalPrice: 8000,
        category: "streaming",
        description: "Compte Netflix personnel - 1 mois",
        icon: "Play",
        color: "from-red-500 to-red-600",
        rating: 4.9,
        reviews: 500,
        features: JSON.stringify([
          "Compte personnel",
          "Qualité 4K",
          "Sans publicité",
        ]),
        stock: 50,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Netflix 5 écrans 4K",
        price: 10000,
        originalPrice: 12000,
        category: "streaming",
        description: "Abonnement Netflix 5 écrans 4K - 1 mois",
        icon: "Play",
        color: "from-red-500 to-red-600",
        rating: 5.0,
        reviews: 300,
        features: JSON.stringify(["5 écrans", "Qualité 4K", "Sans publicité"]),
        stock: 30,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Prime Vidéo",
        price: 2500,
        originalPrice: 3000,
        category: "streaming",
        description: "Abonnement Prime Vidéo - 1 mois",
        icon: "Play",
        color: "from-blue-500 to-blue-600",
        rating: 4.7,
        reviews: 600,
        features: JSON.stringify([
          "Streaming illimité",
          "Qualité HD",
          "Sans publicité",
        ]),
        stock: 70,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Disney+",
        price: 4000,
        originalPrice: 5000,
        category: "streaming",
        description: "Abonnement Disney+ - 1 mois",
        icon: "Play",
        color: "from-blue-400 to-blue-700",
        rating: 4.7,
        reviews: 400,
        features: JSON.stringify([
          "Disney, Marvel, Star Wars",
          "Qualité HD",
          "Sans publicité",
        ]),
        stock: 60,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Snapchat+",
        price: 2500,
        originalPrice: 3000,
        category: "social",
        description: "Abonnement Snapchat+ - 1 mois",
        icon: "Star",
        color: "from-yellow-400 to-yellow-600",
        rating: 4.6,
        reviews: 200,
        features: JSON.stringify([
          "Fonctionnalités exclusives",
          "Badge Snapchat+",
          "Priorité support",
        ]),
        stock: 40,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Spotify",
        price: 2500,
        originalPrice: 3000,
        category: "music",
        description: "Abonnement Spotify Premium - 1 mois",
        icon: "Music",
        color: "from-green-500 to-green-600",
        rating: 4.8,
        reviews: 1000,
        features: JSON.stringify([
          "Musique illimitée",
          "Sans publicité",
          "Qualité HD",
        ]),
        stock: 100,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Spotify Annuel",
        price: 20000,
        originalPrice: 25000,
        category: "music",
        description: "Abonnement Spotify Premium - 1 an",
        icon: "Music",
        color: "from-green-500 to-green-600",
        rating: 4.9,
        reviews: 300,
        features: JSON.stringify([
          "Musique illimitée",
          "Sans publicité",
          "Qualité HD",
        ]),
        stock: 20,
        popular: false,
        duration: "12 mois",
      },
      {
        name: "IPTV",
        price: 4000,
        originalPrice: 5000,
        category: "tv",
        description: "Abonnement IPTV - 1 mois",
        icon: "Tv",
        color: "from-purple-500 to-purple-700",
        rating: 4.5,
        reviews: 150,
        features: JSON.stringify([
          "Chaînes internationales",
          "Qualité HD",
          "Replay inclus",
        ]),
        stock: 50,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Crunchyroll",
        price: 2500,
        originalPrice: 3000,
        category: "anime",
        description: "Abonnement Crunchyroll - 1 mois",
        icon: "Star",
        color: "from-orange-400 to-orange-600",
        rating: 4.7,
        reviews: 200,
        features: JSON.stringify([
          "Animes illimités",
          "Simulcast",
          "Qualité HD",
        ]),
        stock: 40,
        popular: false,
        duration: "1 mois",
      },
      {
        name: "Pièces e-football 100 Coin",
        price: 2000,
        originalPrice: 2500,
        category: "gaming",
        description: "100 pièces e-football",
        icon: "GamepadIcon",
        color: "from-blue-500 to-blue-600",
        rating: 4.5,
        reviews: 100,
        features: JSON.stringify([
          "Livraison instantanée",
          "Coins authentiques",
        ]),
        stock: 100,
        popular: false,
        duration: "Instantané",
      },
    ],
  });
  console.log("Produits insérés !");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    prisma.$disconnect();
  });
